### ISSUE TITLE
华为应用市场

### ISSUE THREAD

**Issue by leeima** [Adpro-Team/GKD_subscription#131]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是否属于 [本项目维护的规则](https://github.com/Adpro-Team/GKD_subscription) 导致

- [X] 确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 确保提供下列BUG描述及其复现步骤, 否则我同意维护者直接关闭问题

### 请输入 误触/不执行规则 的界面的快照, BUG描述及其复现步骤(视频/截图)或者生成的快照链接, 也可在后面补充其它信息
请注意: 
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在7日内予以回复，否则会被关闭

华为应用市场无法跳过开屏广告，规则已全部打开https://github.com/gkd-kit/inspect/files/15160756/file.zip
![4926b7a876dfde0a4b6c7b983c39a7b](https://github.com/Adpro-Team/GKD_subscription/assets/84554107/fbc28d04-88aa-466e-ab2d-403d0d8f6ee6)

**Comment by adproqwq** [comment]
是快照，不是日志
