### ISSUE TITLE
无法点击NGA开屏推广

### ISSUE THREAD

**Issue by SANA4149** [Adpro-Team/GKD_subscription#133]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是否属于 [本项目维护的规则](https://github.com/Adpro-Team/GKD_subscription) 导致

- [X] 确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 确保提供下列BUG描述及其复现步骤, 否则我同意维护者直接关闭问题

### 请输入 误触/不执行规则 的界面的快照, BUG描述及其复现步骤(视频/截图)或者生成的快照链接, 也可在后面补充其它信息
请注意: 
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在7日内予以回复，否则会被关闭

推广如图，9.1.1版本的NGA
https://i.gkd.li/i/15172694
同时我注意到全局设定的开屏广告被强制禁用（有两倍的设定是因为发现失效后使用另一个订阅尝试解决问题，然而并没有）
https://i.gkd.li/i/15172705

**Comment by adproqwq** [comment]
> 推广如图，9.1.1版本的NGA https://i.gkd.li/i/15172694

29946ac

> 同时我注意到全局设定的开屏广告被强制禁用

因为有专门给这个应用适配的开屏规则，所以全局开屏是默认禁用的。
