### ISSUE TITLE
AH视频

### ISSUE THREAD

**Issue by wuwei0727** [Adpro-Team/GKD_subscription#145]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是否属于 [本项目维护的规则](https://github.com/Adpro-Team/GKD_subscription) 导致

- [X] 确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 确保提供下列BUG描述及其复现步骤, 否则我同意维护者直接关闭问题

### 请输入 误触/不执行规则 的界面的快照, BUG描述及其复现步骤(视频/截图)或者生成的快照链接, 也可在后面补充其它信息
请注意: 
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在7日内予以回复，否则会被关闭

这些都是没有关闭广告的

开屏广告快照：https://i.gkd.li/i/15258457
播放视频快照1：https://i.gkd.li/i/15258500
播放视频快照2：https://i.gkd.li/i/15258557
播放视频快照3：https://i.gkd.li/i/15258570
播放视频快照4：https://i.gkd.li/i/15258575

**Comment by wuwei0727** [comment]
这些都是没有关闭广告的

**Comment by adproqwq** [comment]
7064d24

**Comment by wuwei0727** [comment]
你好，刚刚试了下你昨天更新的，好像还有一些问题。下面是视频文件，快照不好提现出来
[2024-05.zip](https://github.com/Adpro-Team/GKD_subscription/files/15269402/2024-05.zip)

**Comment by adproqwq** [comment]
> 下面是视频文件，快照不好提现出来

需要快照定位问题，误触页面的就行，有没有广告不重要
