### ISSUE TITLE
优酷暂停时中间的广告

### ISSUE THREAD

**Issue by suppermanzero** [Adpro-Team/GKD_subscription#45]
### 请输入需要添加规则的界面的快照或者生成的链接, 也可在后面补充其它信息
请注意:
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在7日内予以回复，否则会被关闭

https://i.gkd.li/import/14321461

**Comment by suppermanzero** [comment]
优酷播放时右下角的广告：https://i.gkd.li/import/14321461

优酷暂停时中间的广告：https://i.gkd.li/import/14321469

**Comment by adproqwq** [comment]
https://i.gkd.li/import/14321401

**Comment by adproqwq** [comment]
aad1c0e
