### ISSUE TITLE
腾讯视频开屏广告无法跳过

### ISSUE THREAD

**Issue by binkwong** [Adpro-Team/GKD_subscription#49]
### 请输入 误触/不执行规则 的界面的快照或者生成的快照链接, 也可在后面补充其它信息
请注意:
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在7日内予以回复，否则会被关闭

腾讯视频开屏广告无法跳过
手机：Magic5至臻版

**Comment by adproqwq** [comment]
无快照

**Comment by tille1229** [comment]
快照地址：https://i.gkd.li/import/14534192

**Comment by adproqwq** [comment]
> 快照地址：https://i.gkd.li/import/14534192

现有规则有效

**Comment by tille1229** [comment]
清空日志后，查看规则日志记录确认是执行的，但并没有跳过广告。

**Comment by AIsouler** [comment]
需使用clickcenter

**Comment by adproqwq** [comment]
e6f1cc5
