### ISSUE TITLE
创维智慧云

### ISSUE THREAD

**Issue by ljqjy** [Adpro-Team/GKD_subscription#50]
### 请输入需要添加规则的界面的快照或者生成的链接, 也可在后面补充其它信息
请注意:
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在7日内予以回复，否则会被关闭

请大佬适配创维智慧云APP开屏跳过规则。它有两种倒计时，数字倒计时目前可以顺利跳过，圆形倒计时不能跳过。
[snapshot-1709656558873 (1).zip](https://github.com/Adpro-Team/GKD_subscription/files/14506441/snapshot-1709656558873.1.zip)

**Comment by adproqwq** [comment]
[2393c79](https://github.com/Adpro-Team/GKD_subscription/commit/2393c79b8d2075f3094928402e0b7c3248477ed4)

**Comment by ljqjy** [comment]
能顺利跳过开屏广告了，多谢大佬。我发现另外一个去开屏广告的APP，我不知道它是不是开源的，也不知道它的实现原理和GKD是否一样，但它有个比较方便的地方是可以通过设置浮窗获取控件信息，直接点添加规则就可以。但它不知道什么原因跳过不了创维智慧云的圆形倒计时广告，目前也没发现更新的版本。这是下载网址：https://www.youxiguancha.com/app/26574.html，大佬如果有时间可以看看，我不懂编程，GKD如果有这种便捷添加规则的方式，那就无敌了。希望GKD越来越好，再次感谢。




蓝天
***@***.***







                       
原始邮件
                       
                     

发件人："Adpro"< ***@***.*** &gt;;

发件时间：2024/3/8 19:12

收件人："Adpro-Team/GKD_subscription"< ***@***.*** &gt;;

抄送人："ljqjy"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [Adpro-Team/GKD_subscription] 创维智慧云 (Issue #50)




 
2393c79

**Comment by adproqwq** [comment]
> 我发现另外一个去开屏广告的 APP，我不知道它是不是开源的，也不知道它的实现原理和 GKD 是否一样

原理一样

> 但它有个比较方便的地方是可以通过设置浮窗获取控件信息，直接点添加规则就可以。

你可以去GKD的仓库提issue

**Comment by ljqjy** [comment]
好，谢谢。




蓝天
***@***.***







                       
原始邮件
                       
                     

发件人："Adpro"< ***@***.*** &gt;;

发件时间：2024/3/9 12:08

收件人："Adpro-Team/GKD_subscription"< ***@***.*** &gt;;

抄送人："ljqjy"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [Adpro-Team/GKD_subscription] 创维智慧云 (Issue #50)




  
我发现另外一个去开屏广告的 APP，我不知道它是不是开源的，也不知道它的实现原理和 GKD 是否一样
  
原理一样
  
但它有个比较方便的地方是可以通过设置浮窗获取控件信息，直接点添加规则就可以。
  
你可以去GKD的仓库提issue
