### ISSUE TITLE
小米商城更新提醒

### ISSUE THREAD

**Issue by KamenRevice** [Adpro-Team/GKD_subscription#53]
### 请输入需要添加规则的界面的快照或者生成的链接, 也可在后面补充其它信息
请注意:
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在7日内予以回复，否则会被关闭

快照记录https://i.gkd.li/import/14517594

**Comment by adproqwq** [comment]
无法适配

**Comment by KamenRevice** [comment]
请问是什么原因无法适配？快照无法使用吗？

**Comment by adproqwq** [comment]
> 请问是什么原因无法适配？快照无法使用吗？

需要坐标点击，需要GKD1.7.0支持

**Comment by KamenRevice** [comment]
以更新1.7.0 beta2 版本获取的快照
https://i.gkd.li/i/14553660
