### ISSUE TITLE
增加微信语音自动转文字，现有规则有bug

### ISSUE THREAD

**Issue by hpliu01** [Adpro-Team/GKD_subscription#54]
V36和V37版本的体验了下，不太对，还有bug。
1，开了这条规则，语音会一直播放第一条语音的前2秒，循环播放。
2，我想要的不是他自动播放，只是我长摁了这条语音后有弹出来操作菜单之后自动点“转文字”，和新收到的语音的自动“转文字”，不需要看到语音条模拟长摁转文字，（目的是想实现在开会或者啥不方便听语音时候长摁后自动转文字）。

分享一个快照给你，图上的2个转文字都需要点。
[1709704484535.zip](https://github.com/Adpro-Team/GKD_subscription/files/14517632/1709704484535.zip)

![image](https://github.com/Adpro-Team/GKD_subscription/assets/35831399/3221e078-6c70-431c-83ac-4997e9f1fe25)

**Comment by adproqwq** [comment]
语音旁边的转文字需要另外提供快照

**Comment by adproqwq** [comment]
https://i.gkd.li/i/14538322

**Comment by adproqwq** [comment]
6351234
