### ISSUE TITLE
掌上公交运行中弹出的广告无法跳过

### ISSUE THREAD

**Issue by kunanhai5888** [Adpro-Team/GKD_subscription#56]
### 请输入需要添加规则的界面的快照或者生成的链接, 也可在后面补充其它信息
请注意:
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在7日内予以回复，否则会被关闭

https://i.gkd.li/import/14548109

**Comment by adproqwq** [comment]
1df5112

**Comment by kunanhai5888** [comment]
You're really amazing,thank you very much!
