### ISSUE TITLE
华尔街见闻开屏广告无法跳过。

### ISSUE THREAD

**Issue by bayosolin** [Adpro-Team/GKD_subscription#58]
### 请输入 误触/不执行规则 的界面的快照或者生成的快照链接, 也可在后面补充其它信息
请注意:
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在7日内予以回复，否则会被关闭

https://i.gkd.li/i/14525329
快照在此，有空帮忙看看下面我写的规则没有什么效果。
{
  id: 'com.wallstreetcn.news',
  name: '华尔街见闻',
  groups: [
    {
      name: '开屏广告',
      key: 0,
      activityIds: 'com.wallstreetcn.news.ProxyMainActivity',
      rules: 
         'TextView[text="广告"] + TextView[text^="关闭"]',
    
    },
  ]
}

**Comment by AIsouler** [comment]
```
[text="广告"] +2 [text^="关闭"]
```

**Comment by bayosolin** [comment]
好的，我试试

**Comment by bayosolin** [comment]
成功了，这条规则你有空可以同步到上游库里

**Comment by bayosolin** [comment]
现在又发现一个问题，就是首次启动广告会跳过，但存在后台一段后打开，还是会跳出这个广告，无法跳过，稍后录个快照。

**Comment by bayosolin** [comment]
根据你的规则重写了一下，可用。
{
  id: 'com.wallstreetcn.news',
  name: '华尔街见闻',
  groups: [
    {
      name: '开屏广告',
      key: 0,
      activityIds: [
        'com.wallstreetcn.news.ProxyMainActivity'
      ],
      rules: [
        {
          matches: [
            '[text="广告"] +2 [text^="关闭"]'
          ]
        }
      ]
    },
    {
      name: '返回开屏广告',
      key: 3,
      activityIds: [
        'com.wallstreetcn.alien.Root.SplashActivity'
      ],
      rules: [
        {
          matches: [
            '[text="广告"] +2 [text^="关闭"]'
          ]
        }
      ]
    }
  ]
}

**Comment by AIsouler** [comment]
> 根据你的规则重写了一下，可用。 { id: 'com.wallstreetcn.news', name: '华尔街见闻', groups: [ { name: '开屏广告', key: 0, activityIds: [ 'com.wallstreetcn.news.ProxyMainActivity' ], rules: [ { matches: [ '[text="广告"] +2 [text^="关闭"]' ] } ] }, { name: '返回开屏广告', key: 3, activityIds: [ 'com.wallstreetcn.alien.Root.SplashActivity' ], rules: [ { matches: [ '[text="广告"] +2 [text^="关闭"]' ] } ] } ] }

开屏广告不需要设置activityid，你有不跳的情况就是因为限制了activityid
```
{
      key: 0,
      name: '开屏广告',
      matchTime: 10000,
      actionMaximum: 1,
      resetMatch: 'app',
      rules: [
        {
          quickFind: true,
          matches: '[text="广告"] +2 [text^="关闭"]',
          exampleUrls:
            'https://m.gkd.li/57941037/40e483a8-61e7-45a0-ac44-df1f472e2863',
          snapshotUrls: 'https://i.gkd.li/i/14525329',
        },
      ],
    },
```

**Comment by bayosolin** [comment]
谢谢大佬赐教！！我纯新手，原来的规则还是参照模板写的。我把这条引用了，大佬也可以在规则库里，增加一下，方便其他网友。

**Comment by AIsouler** [comment]
> 谢谢大佬赐教！！我纯新手，原来的规则还是参照模板写的。我把这条引用了，大佬也可以在规则库里，增加一下，方便其他网友。

https://github.com/Snoopy1866/blogs/tree/main/software/gkd
