### ISSUE TITLE
最新版本得力E+开屏适配

### ISSUE THREAD

**Issue by drw2005** [Adpro-Team/GKD_subscription#59]
### 请输入需要添加规则的界面的快照或者生成的链接, 也可在后面补充其它信息
请注意:
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在7日内予以回复，否则会被关闭

https://github.com/gkd-kit/inspect/files/14552987/file.zip

**Comment by adproqwq** [comment]
c4b18de
