### ISSUE TITLE
小米商城更新提醒，使用1.7版本获取快照

### ISSUE THREAD

**Issue by KamenRevice** [Adpro-Team/GKD_subscription#60]
### 请输入需要添加规则的界面的快照或者生成的链接, 也可在后面补充其它信息
请注意:
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在7日内予以回复，否则会被关闭

使用1.7.0 beta2 版本获取的快照
https://i.gkd.li/i/14553660

麻烦大佬适配一下

**Comment by adproqwq** [comment]
无法适配
