### ISSUE TITLE
网易邮箱有时候开屏广告无法跳过，麻烦测试一下

### ISSUE THREAD

**Issue by kaenchen** [Adpro-Team/GKD_subscription#62]
### 请输入 误触/不执行规则 的界面的快照或者生成的快照链接, 也可在后面补充其它信息
请注意:
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在7日内予以回复，否则会被关闭

网易邮箱有时候开屏广告无法跳过，麻烦测试一下

**Comment by adproqwq** [comment]
无快照
