### ISSUE TITLE
网易邮箱无法跳过开屏广告

### ISSUE THREAD

**Issue by kaenchen** [Adpro-Team/GKD_subscription#63]
### 请输入 误触/不执行规则 的界面的快照或者生成的快照链接, 也可在后面补充其它信息
请注意:
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在7日内予以回复，否则会被关闭

![Screenshot_20240316_101716_com netease mobimail](https://github.com/Adpro-Team/GKD_subscription/assets/79465568/81b10e86-f4c7-47a4-9c66-233df7069dac)
![Screenshot_20240316_101656_com netease mobimail](https://github.com/Adpro-Team/GKD_subscription/assets/79465568/ce5256ec-763d-4b97-903f-281480d3e1c0)

**Comment by adproqwq** [comment]
是快照不是截图，截图没有任何用处

**Comment by adproqwq** [comment]
我先关了issue，你后续把快照发到这里我再重新打开
