### ISSUE TITLE
微博关注弹窗

### ISSUE THREAD

**Issue by tangwenlongNO1** [Adpro-Team/GKD_subscription#64]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 确保提供正确的快照, 否则我同意维护者直接关闭问题

### 请输入需要添加规则的界面的快照或者生成的链接, 也可在后面补充其它信息
请注意:
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在7日内予以回复，否则会被关闭

[1710733731849.zip](https://github.com/Adpro-Team/GKD_subscription/files/14631270/1710733731849.zip)

**Comment by adproqwq** [comment]
无法适配
