### ISSUE TITLE
大姨妈app开屏广告无法跳过

### ISSUE THREAD

**Issue by yankangwin** [Adpro-Team/GKD_subscription#67]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是否属于 [本项目维护的规则](https://github.com/Adpro-Team/GKD_subscription) 导致

- [X] 确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 确保提供下列BUG描述及其复现步骤, 否则我同意维护者直接关闭问题

### 请输入 误触/不执行规则 的界面的快照, BUG描述及其复现步骤(视频/截图)或者生成的快照链接, 也可在后面补充其它信息
请注意: 
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在7日内予以回复，否则会被关闭

[1710932298245.zip](https://github.com/Adpro-Team/GKD_subscription/files/14665277/1710932298245.zip)
开屏广告无法跳过，快照文件如上。

**Comment by adproqwq** [comment]
6be604e
