### ISSUE TITLE
奇妙应用安装提示

### ISSUE THREAD

**Issue by fewkisses** [Adpro-Team/GKD_subscription#69]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 确保提供正确的快照, 否则我同意维护者直接关闭问题

### 请输入需要添加规则的界面的快照或者生成的链接, 也可在后面补充其它信息
请注意:
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在7日内予以回复，否则会被关闭

[奇妙应用_updateActivity-1710958813725.zip](https://github.com/Adpro-Team/GKD_subscription/files/14670976/_updateActivity-1710958813725.zip)

**Comment by adproqwq** [comment]
点一次不再提醒就行了，没有必要写规则

**Comment by adproqwq** [comment]
除非你可以提供写该条规则的必要性
