### ISSUE TITLE
油管播放页面向下展开的广告，右边的那个叉

### ISSUE THREAD

**Issue by fewkisses** [Adpro-Team/GKD_subscription#79]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 确保提供正确的快照, 否则我同意维护者直接关闭问题
- [X] 确保已阅读[#74](https://github.com/Adpro-Team/GKD_subscription/discussions/74)中的所有通知，并确认需适配的 APP 没有与它们精神相违背，否则我同意维护者直接关闭问题

### 请输入需要添加规则的界面的快照或者生成的链接, 也可在后面补充其它信息
请注意:
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在7日内予以回复，否则会被关闭

[YouTube_MainActivity-1711559457309.zip](https://github.com/Adpro-Team/GKD_subscription/files/14776878/YouTube_MainActivity-1711559457309.zip)

**Comment by adproqwq** [comment]
b07324a
