### ISSUE TITLE
推特个人页面的广告，有时候不识别或者识别到后不触发二次点击“我不喜欢这个广告”

### ISSUE THREAD

**Issue by fewkisses** [Adpro-Team/GKD_subscription#81]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是否属于 [本项目维护的规则](https://github.com/Adpro-Team/GKD_subscription) 导致

- [X] 确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 确保提供下列BUG描述及其复现步骤, 否则我同意维护者直接关闭问题

### 请输入 误触/不执行规则 的界面的快照, BUG描述及其复现步骤(视频/截图)或者生成的快照链接, 也可在后面补充其它信息
请注意: 
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在7日内予以回复，否则会被关闭

[X_ProfileActivity-1711561289439.zip](https://github.com/Adpro-Team/GKD_subscription/files/14779208/X_ProfileActivity-1711561289439.zip)

[X_ProfileActivity-1711561269111.zip](https://github.com/Adpro-Team/GKD_subscription/files/14779205/X_ProfileActivity-1711561269111.zip)

**Comment by adproqwq** [comment]
af2f5ad
