### ISSUE TITLE
小米应用商店

### ISSUE THREAD

**Issue by zaonie** [Adpro-Team/GKD_subscription#88]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是否属于 [本项目维护的规则](https://github.com/Adpro-Team/GKD_subscription) 导致

- [X] 确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 确保提供下列BUG描述及其复现步骤, 否则我同意维护者直接关闭问题

### 请输入 误触/不执行规则 的界面的快照, BUG描述及其复现步骤(视频/截图)或者生成的快照链接, 也可在后面补充其它信息
请注意: 
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在7日内予以回复，否则会被关闭

![Screenshot_2024-03-30-17-12-14-373_com xiaomi market](https://github.com/Adpro-Team/GKD_subscription/assets/48220895/e5a62643-29f0-475e-8979-dfb7d3995eb5)

小米应用商店首页开屏广告。
以前是可以自动跳过的，现在失效了。
操作就是直接点开小米应用商店。小米应用商店的版本是4.6.0。
已经检查，现在open的issue里没有该问题，所以提交。

**Comment by adproqwq** [comment]
需要快照。暂时关闭，等补充快照后会重新打开

**Comment by zaonie** [comment]
[智能服务-1711797248036.zip](https://github.com/Adpro-Team/GKD_subscription/files/14811675/-1711797248036.zip)
![1711796537226_100](https://github.com/Adpro-Team/GKD_subscription/assets/48220895/85ad7b2d-a113-4ee0-bdf0-62e3296fd144)
补充快照如上。

**Comment by adproqwq** [comment]
> 补充快照如上。

快照无效，请确认已经给予了GKD截屏权限

**Comment by adproqwq** [comment]
规则有效

**Comment by brucevanfdm** [comment]
我这里也有同样的问题，看了下小米应用商店这个开屏广告应该是小米一个内置应用（智能服务：com.miui.systemAdSolution）弹出的，我生成的快照跟楼上那位的一样，也是显示智能服务，但无法抓取页面内容。

**Comment by adproqwq** [comment]
> 我这里也有同样的问题，看了下小米应用商店这个开屏广告应该是小米一个内置应用（智能服务：com.miui.systemAdSolution）弹出的，我生成的快照跟楼上那位的一样，也是显示智能服务，但无法抓取页面内容。 @adproqwq 
> 
> 另一个解决方案是关闭小米智能服务在其他应用上层显示的特殊权限

全局广告是否开启？

**Comment by adproqwq** [comment]
> 我这里也有同样的问题，看了下小米应用商店这个开屏广告应该是小米一个内置应用（智能服务：com.miui.systemAdSolution）弹出的，我生成的快照跟楼上那位的一样，也是显示智能服务，但无法抓取页面内容。 @adproqwq 
> 
> 另一个解决方案是关闭小米智能服务在其他应用上层显示的特殊权限

全局开屏是否开启？

**Comment by adproqwq** [comment]
请见AIsouler/GKD_subscription#154

**Comment by SteveSteve666** [comment]
甘霖的那个全局可以跳

**Comment by SteveSteve666** [comment]
> 接下来的讨论请到：AIsouler/GKD_subscription#154

最新的解决了

**Comment by adproqwq** [comment]
362741d
