### ISSUE TITLE
彩云天气

### ISSUE THREAD

**Issue by TianMiao8152** [Adpro-Team/GKD_subscription#89]
# 目前只能点击开屏广告，插片广告失效
## 以下是相关截图和快照

广告
[snapshot-1711863959769.zip](https://github.com/Adpro-Team/GKD_subscription/files/14814246/snapshot-1711863959769.zip)

***

广告
[snapshot-1711863943562.zip](https://github.com/Adpro-Team/GKD_subscription/files/14814247/snapshot-1711863943562.zip)

***

广告
[snapshot-1711863851042.zip](https://github.com/Adpro-Team/GKD_subscription/files/14814248/snapshot-1711863851042.zip)

***

点击收起顶部工具栏
[snapshot-1711863804219.zip](https://github.com/Adpro-Team/GKD_subscription/files/14814249/snapshot-1711863804219.zip)
顶部工具栏收起后
[snapshot-1711866001297.zip](https://github.com/AIsouler/GKD_subscription/files/14814359/snapshot-1711866001297.zip)

***

广告
[snapshot-1711863756851.zip](https://github.com/Adpro-Team/GKD_subscription/files/14814250/snapshot-1711863756851.zip)
一个不同样式的同种广告
[snapshot-1711865983949.zip](https://github.com/AIsouler/GKD_subscription/files/14814357/snapshot-1711865983949.zip)

**Comment by TianMiao8152** [comment]
https://github.com/Adpro-Team/GKD_subscription/pull/91

**Comment by adproqwq** [comment]
27aae87
