### ISSUE TITLE
小米应用商店更新软件时弹出开启推送弹窗

### ISSUE THREAD

**Issue by pheotry** [Adpro-Team/GKD_subscription#90]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 确保提供正确的快照, 否则我同意维护者直接关闭问题
- [X] 确保已阅读[#74](https://github.com/Adpro-Team/GKD_subscription/discussions/74)中的所有通知，并确认需适配的 APP 没有与它们精神相违背，否则我同意维护者直接关闭问题

### 请输入需要添加规则的界面的快照或者生成的链接, 也可在后面补充其它信息
请注意:
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在7日内予以回复，否则会被关闭

[应用商店_UpdateListActivity-1711554330330.zip](https://github.com/Adpro-Team/GKD_subscription/files/14814405/_UpdateListActivity-1711554330330.zip)

不开启推送的话，每次重启应用商店更新软件时都会弹出这个提示，100%触发。

**Comment by adproqwq** [comment]
现有规则有效
