### ISSUE TITLE
[误触]高德地图 局部广告-首页-广告卡片

### ISSUE THREAD

**Issue by Snoopy1866** [Adpro-Team/GKD_subscription#98]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是否属于 [本项目维护的规则](https://github.com/Adpro-Team/GKD_subscription) 导致

- [X] 确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 确保提供下列BUG描述及其复现步骤, 否则我同意维护者直接关闭问题

### 请输入 误触/不执行规则 的界面的快照, BUG描述及其复现步骤(视频/截图)或者生成的快照链接, 也可在后面补充其它信息
请注意: 
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在7日内予以回复，否则会被关闭

https://i.gkd.li/i/14886366

**Comment by Snoopy1866** [comment]
```
ViewGroup >(1,4) ViewGroup[childCount>=2 && childCount<=4] > ViewGroup + @ViewGroup[childCount=1][visibleToUser=true][clickable=true] > ImageView[desc=null || desc="关闭"][clickable=false]
```

**Comment by adproqwq** [comment]
a60951d

**Comment by Snoopy1866** [comment]
笑死

**Comment by adproqwq** [comment]
> 笑死

压垮这脆弱的规则的最后一根稻草就是你的广东博物馆快照
